version: '3.1'

services:

  mongodb:
    image: mongo:4.4-focal
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE_NAME}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - ${MONGO_DB_FOLDER}:/data/db

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ${REDIS_FOLDER}:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redisinsight
    ports:
      - ${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}
    volumes:
      - ${REDISINSIGHT_FOLDER}:/db