version: '3.1'

services:

  mongodb:
    image: mongo:4.4-focal
    restart: always
    container_name: mongodb-house
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE_NAME}
    ports:
      - ${MONGO_DB_PORT_EXTERNAL}:${MONGO_DB_PORT_INTERNAL}
    volumes:
      - ${MONGO_DB_FOLDER}:/data/db

  redis:
    image: redis:latest
    restart: always
    container_name: redis-house
    ports:
      - ${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}
    volumes:
      - ${REDIS_FOLDER}:/data

  redisinsight:
    build:
      context: .
      dockerfile: ./docker/redisinsight/Dockerfile
    restart: always
    container_name: redisinsight-house
    ports:
      - ${REDISINSIGHT_PORT_EXTERNAL}:${REDISINSIGHT_PORT_INTERNAL}
    volumes:
      - ${REDISINSIGHT_FOLDER}:/db