name: Client Workflow.
on:
  pull_request:
jobs:
  merge-request-linting-client:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code.
        uses: actions/checkout@v3
      - name: Cache dependencies.
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json ') }}
      - name: Install dependencies.
        run: npm ci
        working-directory: client
      - name: Linting code.
        run: npm run lint
        working-directory: client