name: Lint Server Code
on:
  pull_request:
    branches:
      - 'master'
jobs:
  lint-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Cache dependencies.
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles( '**/package-lock.json' ) }}
      - name: Install dependencies.
        run: npm ci
      - name: Run linter.
        run: npm run lint